// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Bulma$ReactTemplate = require("../../Bulma.bs.js");

import './Notification.styl'
;

var component = ReasonReact.statelessComponent("Notification-ReactTemplate");

function make(active, heading, message, $staropt$star, _children) {
  var theme = $staropt$star !== undefined ? $staropt$star : /* Primary */6;
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var theme$1 = Bulma$ReactTemplate.string_of_theme(theme);
              var style = {
                opacity: active ? "1" : "0"
              };
              if (heading !== undefined) {
                return React.createElement("div", {
                            className: "Notification Notification__expanded message " + theme$1,
                            style: style
                          }, React.createElement("div", {
                                className: "message-header"
                              }, heading, React.createElement("button", {
                                    className: "delete"
                                  })), React.createElement("div", {
                                className: "message-body"
                              }, message));
              } else {
                return React.createElement("div", {
                            className: "Notification Notification__basic notification " + theme$1,
                            style: style
                          }, React.createElement("button", {
                                className: "delete"
                              }), message);
              }
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/*  Not a pure module */
