// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Box$ReactTemplate = require("../Box/Box.bs.js");
var Button$ReactTemplate = require("../Button/Button.bs.js");
var Spacer$ReactTemplate = require("../Spacer/Spacer.bs.js");
var Heading$ReactTemplate = require("../Heading/Heading.bs.js");
var Stateful$ReactTemplate = require("../Stateful/Stateful.bs.js");
var Subheading$ReactTemplate = require("../Heading/Subheading.bs.js");
var Notification$ReactTemplate = require("../Notification/Notification.bs.js");

import { hot } from 'react-hot-loader'
;

var component = ReasonReact.reducerComponent("App-ReactTemplate");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Heading$ReactTemplate.make(/* array */["Bulma + ReasonReact"])), ReasonReact.element(undefined, undefined, Subheading$ReactTemplate.make(/* array */["Playground"])), ReasonReact.element(undefined, undefined, Spacer$ReactTemplate.make(30, /* array */[])), ReasonReact.element(undefined, undefined, Box$ReactTemplate.make(/* array */[ReasonReact.element(undefined, undefined, Stateful$ReactTemplate.make(/* array */[]))])), ReasonReact.element(undefined, undefined, Box$ReactTemplate.make(/* array */[
                                  ReasonReact.element(undefined, undefined, Button$ReactTemplate.make("Toggle Message", (function (_event) {
                                              return Curry._1(self[/* send */3], /* ToggleMessage */0);
                                            }), /* Info */7, undefined, /* array */[])),
                                  ReasonReact.element(undefined, undefined, Button$ReactTemplate.make("Toggle Notification", (function (_event) {
                                              return Curry._1(self[/* send */3], /* ToggleNotification */1);
                                            }), /* Warning */9, undefined, /* array */[]))
                                ])), ReasonReact.element(undefined, undefined, Notification$ReactTemplate.make(self[/* state */1][/* showMessage */0], "I'm a notification", "Body", /* Info */7, /* array */[])), ReasonReact.element(undefined, undefined, Notification$ReactTemplate.make(self[/* state */1][/* showNotification */1], undefined, "Body", /* Warning */9, /* array */[])));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* showMessage */false,
                      /* showNotification */false
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[
                            /* showMessage */state[/* showMessage */0],
                            /* showNotification */!state[/* showNotification */1]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* showMessage */!state[/* showMessage */0],
                            /* showNotification */state[/* showNotification */1]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var comp = ReasonReact.wrapReasonForJs(component, (function (_jsProps) {
        return make(/* array */[]);
      }));

export default hot(module)(comp)
;

exports.component = component;
exports.make = make;
exports.comp = comp;
/*  Not a pure module */
