// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Box$ReactTemplate = require("../../components/Box/Box.bs.js");
var Page$ReactTemplate = require("../../components/Page/Page.bs.js");
var Button$ReactTemplate = require("../../components/Button/Button.bs.js");
var SearchBar$ReactTemplate = require("../../components/SearchBar/SearchBar.bs.js");

var component = ReasonReact.reducerComponent("Dashboard-ReactTemplate");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, Page$ReactTemplate.make("Dashboard", undefined, /* array */[ReasonReact.element(undefined, undefined, Box$ReactTemplate.make("Search", /* array */[
                                        ReasonReact.element(undefined, undefined, SearchBar$ReactTemplate.make(self[/* state */1][/* query */0], (function ($$event) {
                                                    return Curry._1(self[/* send */3], /* UpdateQuery */[$$event.target.value]);
                                                  }), undefined, /* array */[])),
                                        ReasonReact.element(undefined, undefined, Button$ReactTemplate.make("Home", (function (_event) {
                                                    return ReasonReact.Router[/* push */0]("/dashboard");
                                                  }), /* Primary */6, undefined, /* array */[])),
                                        ReasonReact.element(undefined, undefined, Button$ReactTemplate.make("View Details", (function (_event) {
                                                    return ReasonReact.Router[/* push */0]("/show/10");
                                                  }), /* Warning */10, undefined, /* array */[]))
                                      ]))]));
            }),
          /* initialState */(function (param) {
              return /* record */[/* query */""];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              return /* Update */Block.__(0, [/* record */[/* query */action[0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
