// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Heading$ReactTemplate = require("../Heading/Heading.bs.js");
var Fragment$ReactTemplate = require("../Fragment/Fragment.bs.js");
var Subheading$ReactTemplate = require("../Heading/Subheading.bs.js");

var component = ReasonReact.statelessComponent("Page-ReactTemplate");

function make(heading, subheading, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_state) {
              return React.createElement("div", {
                          className: "Page"
                        }, ReasonReact.element(undefined, undefined, Heading$ReactTemplate.make(/* array */[heading])), Belt_Option.getWithDefault(Belt_Option.map(subheading, (function (text) {
                                    return ReasonReact.element(undefined, undefined, Subheading$ReactTemplate.make(/* array */[text]));
                                  })), null), ReasonReact.element(undefined, undefined, Fragment$ReactTemplate.make(children)));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
