// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function string_of_theme(th) {
  switch (th) {
    case 0 : 
        return "";
    case 1 : 
        return "is-white";
    case 2 : 
        return "is-light";
    case 3 : 
        return "is-dark";
    case 4 : 
        return "is-black";
    case 5 : 
        return "is-text";
    case 6 : 
        return "is-primary";
    case 7 : 
        return "is-link";
    case 8 : 
        return "is-info";
    case 9 : 
        return "is-success";
    case 10 : 
        return "is-warning";
    case 11 : 
        return "is-danger";
    
  }
}

exports.string_of_theme = string_of_theme;
/* No side effect */
