// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Bulma$ReactTemplate = require("../../Bulma.bs.js");

var component = ReasonReact.statelessComponent("ProgressBar-ReactTemplate");

function make($staropt$star, value, $staropt$star$1, _children) {
  var theme = $staropt$star !== undefined ? $staropt$star : /* Link */7;
  var max = $staropt$star$1 !== undefined ? $staropt$star$1 : 100;
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var theme$1 = Bulma$ReactTemplate.string_of_theme(theme);
              var percent = (value / max * 100).toFixed(2) + "%";
              var value$1 = String(value);
              var max$1 = String(max);
              return React.createElement("progress", {
                          className: "progress " + theme$1,
                          max: max$1,
                          value: value$1
                        }, percent);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
